version: '3'

services:
  airflow:
    image: apache/airflow:2.7.1
    container_name: airflow_p1
    depends_on:
      - postgres
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow_db
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - _AIRFLOW_WWW_USER_USERNAME=airflow
      - _AIRFLOW_WWW_USER_PASSWORD=airflow
    ports:  
      - "8081:8080"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
    command: standalone

  postgres:
    image: postgres:13 
    container_name: airflow-postgres_p1 
    environment:
      POSTGRES_USER: airflow 
      POSTGRES_PASSWORD: airflow 
      POSTGRES_DB: airflow_db
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
 
volumes:
  postgres_data:

